name: Unzip and Commit

on:
  push:
    paths:
      - "vozilo_mvp.zip"
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          sudo apt-get install -y unzip
          unzip -o vozilo_mvp.zip -d ./unzipped

      - name: Move files
        run: |
          cp -r ./unzipped/* ./
          rm -rf ./unzipped vozilo_mvp.zip

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped vozilo_mvp.zip"
          git push
